### ISSUE TITLE
Apple M1 arm64-simulator support

### ISSUE THREAD

**Issue by Arlindo-g** [configcat/swift-sdk#15]
### Describe the bug

Run app on simulator with ConfigCat pod and building fails.  Missing architecture arm64-simulator

### To reproduce

Using the latest version of Xcode (12.5.1) on most recent's Apple MacBook Pro (processor Apple M1), install ConfigCat (7.2.0) install using Cocoapods (1.11.0)

1. Attempt to Build 
2. Observe error: `Framework not found ConfigCat`

### Expected behavior

Builds successfully with no errors or warnings

### SDK version

ConfigCat (7.2.0)

### Platform

MacBook Pro (13-inch, M1, 2020) 
macOS Big Sur 11.5.2 (20G95)

**Comment by Arlindo-g** [comment]
Probably just have to use an `xcframework` as the vender framework and specify that in the podspec. [Xcframework with Cocoapods](https://anuragajwani.medium.com/distributing-universal-ios-frameworks-as-xcframeworks-using-cocoapods-699c70a5c961)

**Comment by z4kn4fein** [comment]
Hi @Arlindo-g , thank you for reaching out!

What you reported seems a bit odd to me as we do not distribute pre-compiled binaries to specific architecture types. 
In my understanding (please, correct me if I'm wrong), conversion to xcframework would make sense only if we'd produce pre-built frameworks, but we package only our source files, and Cocoapods and SPM does the compilation based on your project settings.

I also tried our [iOS sample](https://github.com/configcat/swift-sdk/tree/master/samples/ios) on an M1 machine (Big Sur 11.5.2, Xcode 12.5) that uses Cocoapods, and it started without issues. I did the same with another sample app that uses SPM and it worked too.

Are you sure that it's not something with your Xcode project settings? 
If so, can you give me a sample project that has this issue and I can use it for further investigation?

Thanks in advance!

**Comment by Arlindo-g** [comment]
You are totally correct. Sorry for adding a pointless issue. It happened to be some false positive situation where with another Pod, but I didn't clear out any derived data before updating it. 

Thanks for the quick response!
