### ISSUE TITLE
Xcode 12 different definitions in different modules build error

### ISSUE THREAD

**Issue by JohnKuan** [configcat/swift-sdk#7]
Hi,

One of our dependency (CometChatPro) has a namespace conflict in the compile run time. This happens in XCode 12.

The affected class object is 

`
'User' has different definitions in different modules; first difference is definition in module 'CometChatPro.Swift' found super class with type 'AppEntity'
User: App
`

Additionally, there are many developers facing this issue with other pods as well.
https://developer.apple.com/forums/thread/658012

Could you look into this issue as it does not give us confidence in integrating ConfigCat SDK with our project.

Thanks

**Comment by z4kn4fein** [comment]
Hi,

Thanks for reporting this issue, we are going to work on a solution now.

**Comment by z4kn4fein** [comment]
The new version with the fix is on the way, I renamed the `User` to `CCUser`.

**Comment by JohnKuan** [comment]
Hi @z4kn4fein 

I have made a pull request to this issue. Please have a look and see if my recommendation makes sense. If the fix to use `CCUser` is better for your company's use cases, please proceed to make the necessary changes and I will adopt the changes accordingly on my company's project.

https://github.com/configcat/swift-sdk/pull/8

**Comment by z4kn4fein** [comment]
Hi @JohnKuan 

We approved your changes, after the resolution of the remaining conflicts I'll merge and release a new version from it.

**Comment by z4kn4fein** [comment]
Released in [7.0.0](https://github.com/configcat/swift-sdk/releases/tag/7.0.0)
